### ISSUE TITLE
Fails when browserify and require is used

### ISSUE THREAD

**Issue by jukkasi** [voronianski/ngKookies#2]
Not sure what lines 8-16 are about in ngKookies.js but it totally breaks the whole library when require('ngkookies) is used.

I get error like Uncaught TypeError: undefined is not a function and line numbers for errors don't make any sense.

Removing lines 8-16 and  introducing the module like

'use strict';

angular.module('ngKookies', []).provider('$kookies', function () {
...

works just fine

**Comment by voronianski** [comment]
@jukkasi do you aware of UMD pattern https://github.com/umdjs/umd? 

Did you have proper setup with browserify?

**Comment by jukkasi** [comment]
Thank you for pointing me out UMD

I tried transformations mentioned in http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html but still no luck

**Comment by renestalder** [comment]
I have the same problem.

**Comment by voronianski** [comment]
@renestalder it's Angular's issue, see links here -  https://github.com/likeastore/ngDialog/issues/187#issuecomment-78991106
