### ISSUE TITLE
cookie value not encoded properly

### ISSUE THREAD

**Issue by scags9876** [voronianski/ngKookies#3]
Tiny example to illustrate the problem:

var foo=123, bar=987;
var cookieValue = {foo:foo,bar:bar};

$kookies.set('cookieName', cookieValue);

I would expect the cookie value to be set to:
"%7B%22foo%22%3A123%2C%22bar%22%3A987%7D"

however, it is set to:
{"foo":123,"bar":987}

Which breaks the specification for well formed cookies, which can have neither double quotes nor commas.

I notice in the source of ngKookies:
           privateMethods.decode = function (s) {
                return config.raw ? s : encodeURIComponent(s);
            };

```
        privateMethods.encode = function (s) {
            return config.raw ? s : decodeURIComponent(s);
        };
```

Shouldn't decode call decodeURIComponent, and encode call encodeURIComponent?

Thanks

**Comment by voronianski** [comment]
@scags9876 thanks for your input! You're right, the typo is now fixed in `0.2.0`.
