### ISSUE TITLE
Unable to set cookie when domain is preset

### ISSUE THREAD

**Issue by c0debreaker** [voronianski/ngKookies#4]
I tried the following but I found out that when domain is present, it doesn't get added to my browser's cookie.
1. $kookies.set(key, value, { domain: 'localhost:3000' }); 
2. $kookies.set(key, value, { domain: 'localhost' }); 
3. $kookies.set(key, value, { domain: 'example.com' }); 

and the only code that work is
$kookies.set(key, value);

I switched to ngKookies from ngCookies in the hopes of being able to share cookies on different applications under a single domain.

Please help.

**Comment by c0debreaker** [comment]
I also tried this code but I'm not sure if it's taking effect. It's because it's not changing the value in chrome dev tools

```
$kookiesProvider.config.domain = 'example.com';
$kookiesProvider.config.path = '/';
```

It was still showing localhost. Here is a screenshot
http://i.imgur.com/7At9xOD.png

**Comment by NioTeX** [comment]
(+1)

**Comment by soumak77** [comment]
+1

**Comment by c0debreaker** [comment]
I think I got this to work a long time ago but couldn't remember :)
